# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-03 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=512, unique=True)),
                ('user_id', models.IntegerField(default=0, editable=False)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('gravatar_id', models.IntegerField(default=0, editable=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('html_url', models.URLField(blank=True, null=True)),
                ('followers_url', models.URLField(blank=True, null=True)),
                ('following_url', models.URLField(blank=True, null=True)),
                ('gists_url', models.URLField(blank=True, null=True)),
                ('starred_url', models.URLField(blank=True, null=True)),
                ('subscriptions_url', models.URLField(blank=True, null=True)),
                ('organizations_url', models.URLField(blank=True, null=True)),
                ('repos_url', models.URLField(blank=True, null=True)),
                ('events_url', models.URLField(blank=True, null=True)),
                ('received_events_url', models.URLField(blank=True, null=True)),
                ('type', models.CharField(max_length=127)),
                ('site_admin', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=127)),
                ('company', models.CharField(max_length=127)),
                ('blog', models.URLField(blank=True, null=True)),
                ('location', models.CharField(max_length=127)),
                ('email', models.CharField(max_length=127)),
                ('bio', models.TextField(blank=True, max_length=512, null=True)),
                ('public_repos', models.IntegerField(default=0, editable=False)),
                ('public_gists', models.IntegerField(default=0, editable=False)),
                ('followers', models.IntegerField(default=0, editable=False)),
                ('following', models.IntegerField(default=0, editable=False)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
            ],
            options={
                'verbose_name': 'GitHub Users',
            },
        ),
    ]
