# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-03 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github_api_usage', '0002_auto_20171003_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gravatar_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='url',
        ),
    ]
