# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-03 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('github_api_usage', '0004_auto_20171003_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
