# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-03 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github_api_usage', '0005_userprofile_added_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='added_at',
            new_name='adding_date',
        ),
    ]
